version: '3.8'

services:
  web:
    image: nginx:alpine # Use Nginx Alpine-based image
    container_name: html-server
    ports:
      - "80:80" # Map port 80 on the host to port 80 in the container
    volumes:
      - ./:/usr/share/nginx/html:ro # Mount the current folder to Nginx's web root as read-only
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Optional custom Nginx configuration
    restart: always # Ensure the container restarts on failure

