---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "my-html-site"
  namespace: "default"
  labels:
    app: "my-html-site"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "my-html-site"
  template:
    metadata:
      labels:
        app: "my-html-site"
    spec:
      containers:
      - name: "my-html-site-1"
        image: "gcr.io/gcp-docker-cicd/my-html-site:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "my-html-site-hpa-cryp"
  namespace: "default"
  labels:
    app: "my-html-site"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "my-html-site"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "my-html-site-service"
  namespace: "default"
  labels:
    app: "my-html-site"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "my-html-site"
  type: "LoadBalancer"
  loadBalancerIP: ""

